import { query, mutation } from "./_generated/server";
import { v } from "convex/values";

// Get all games with search and filter
export const listGames = query({
  args: {
    search: v.optional(v.string()),
    category: v.optional(v.string()),
    multiplayerOnly: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    if (args.search) {
      const searchTerm = args.search; // Narrow the type
      let searchQuery = ctx.db
        .query("games")
        .withSearchIndex("search_games", (q) => q.search("title", searchTerm));

      if (args.category) {
        const category = args.category; // Narrow the type
        searchQuery = searchQuery.filter((q) => q.eq(q.field("category"), category));
      }

      if (args.multiplayerOnly) {
        searchQuery = searchQuery.filter((q) => q.eq(q.field("isMultiplayer"), true));
      }

      return await searchQuery.take(50);
    }

    let query = ctx.db.query("games");

    if (args.category) {
      const category = args.category; // Narrow the type
      query = query.filter((q) => q.eq(q.field("category"), category));
    }

    if (args.multiplayerOnly) {
      query = query.filter((q) => q.eq(q.field("isMultiplayer"), true));
    }

    return await query.order("desc").take(50);
  },
});

// Get single game
export const getGame = query({
  args: { gameId: v.id("games") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.gameId);
  },
});

// Seed some example games
export const seedGames = mutation({
  args: {},
  handler: async (ctx) => {
    const games = [
      {
        title: "Bloons Tower Defense",
        swfUrl: "https://phreshhhhh.github.io/BTD2/bloonstd2.swf",
        thumbnail: "/thumbnails/btd.jpg",
        description: "Strategic tower defense game",
        tags: ["Strategy", "Defense", "Popular"],
        isMultiplayer: false,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Club Penguin",
        swfUrl: "/games/clubpenguin.swf",
        thumbnail: "/thumbnails/clubpenguin.jpg",
        description: "Virtual world MMO",
        tags: ["MMO", "Social", "Adventure"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Robot Unicorn",
        swfUrl: "/games/guitar.swf",
        thumbnail: "/thumbnails/guitar.jpg",
        description: "Rhythm guitar game",
        tags: ["Music", "Rhythm", "Skill"],
        isMultiplayer: false,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Sonny",
        swfUrl: "https://phreshhhhh.github.io/SONNY/sonny-505817f.swf",
        thumbnail: "/thumbnails/stickwar.jpg",
        description: "Strategy war game",
        tags: ["Strategy", "War", "Action"],
        isMultiplayer: false,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "PPG Brawl",
        swfUrl: "https://phreshhhhh.github.io/PP-G/301661_ppg_newgrounds202c.swf",
        thumbnail: "/thumbnails/stickwar.jpg",
        description: "Fighting game",
        tags: ["Action"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      // Add more games here
      {
        title: "Game 9",
        swfUrl: "/games/game9.swf",
        thumbnail: "/thumbnails/game9.jpg",
        description: "Description for Game 9",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 10",
        swfUrl: "/games/game10.swf",
        thumbnail: "/thumbnails/game10.jpg",
        description: "Description for Game 10",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 11",
        swfUrl: "/games/game11.swf",
        thumbnail: "/thumbnails/game11.jpg",
        description: "Description for Game 11",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 12",
        swfUrl: "/games/game12.swf",
        thumbnail: "/thumbnails/game12.jpg",
        description: "Description for Game 12",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 13",
        swfUrl: "/games/game13.swf",
        thumbnail: "/thumbnails/game13.jpg",
        description: "Description for Game 13",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 14",
        swfUrl: "/games/game14.swf",
        thumbnail: "/thumbnails/game14.jpg",
        description: "Description for Game 14",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 15",
        swfUrl: "/games/game15.swf",
        thumbnail: "/thumbnails/game15.jpg",
        description: "Description for Game 15",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 16",
        swfUrl: "/games/game16.swf",
        thumbnail: "/thumbnails/game16.jpg",
        description: "Description for Game 16",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 17",
        swfUrl: "/games/game17.swf",
        thumbnail: "/thumbnails/game17.jpg",
        description: "Description for Game 17",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 18",
        swfUrl: "/games/game18.swf",
        thumbnail: "/thumbnails/game18.jpg",
        description: "Description for Game 18",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 19",
        swfUrl: "/games/game19.swf",
        thumbnail: "/thumbnails/game19.jpg",
        description: "Description for Game 19",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 20",
        swfUrl: "/games/game20.swf",
        thumbnail: "/thumbnails/game20.jpg",
        description: "Description for Game 20",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 21",
        swfUrl: "/games/game21.swf",
        thumbnail: "/thumbnails/game21.jpg",
        description: "Description for Game 21",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 22",
        swfUrl: "/games/game22.swf",
        thumbnail: "/thumbnails/game22.jpg",
        description: "Description for Game 22",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 23",
        swfUrl: "/games/game23.swf",
        thumbnail: "/thumbnails/game23.jpg",
        description: "Description for Game 23",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 24",
        swfUrl: "/games/game24.swf",
        thumbnail: "/thumbnails/game24.jpg",
        description: "Description for Game 24",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 25",
        swfUrl: "/games/game25.swf",
        thumbnail: "/thumbnails/game25.jpg",
        description: "Description for Game 25",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 26",
        swfUrl: "/games/game26.swf",
        thumbnail: "/thumbnails/game26.jpg",
        description: "Description for Game 26",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 27",
        swfUrl: "/games/game27.swf",
        thumbnail: "/thumbnails/game27.jpg",
        description: "Description for Game 27",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 28",
        swfUrl: "/games/game28.swf",
        thumbnail: "/thumbnails/game28.jpg",
        description: "Description for Game 28",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 29",
        swfUrl: "/games/game29.swf",
        thumbnail: "/thumbnails/game29.jpg",
        description: "Description for Game 29",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 30",
        swfUrl: "/games/game30.swf",
        thumbnail: "/thumbnails/game30.jpg",
        description: "Description for Game 30",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 31",
        swfUrl: "/games/game31.swf",
        thumbnail: "/thumbnails/game31.jpg",
        description: "Description for Game 31",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 32",
        swfUrl: "/games/game32.swf",
        thumbnail: "/thumbnails/game32.jpg",
        description: "Description for Game 32",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 33",
        swfUrl: "/games/game33.swf",
        thumbnail: "/thumbnails/game33.jpg",
        description: "Description for Game 33",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 34",
        swfUrl: "/games/game34.swf",
        thumbnail: "/thumbnails/game34.jpg",
        description: "Description for Game 34",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 35",
        swfUrl: "/games/game35.swf",
        thumbnail: "/thumbnails/game35.jpg",
        description: "Description for Game 35",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 36",
        swfUrl: "/games/game36.swf",
        thumbnail: "/thumbnails/game36.jpg",
        description: "Description for Game 36",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 37",
        swfUrl: "/games/game37.swf",
        thumbnail: "/thumbnails/game37.jpg",
        description: "Description for Game 37",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 38",
        swfUrl: "/games/game38.swf",
        thumbnail: "/thumbnails/game38.jpg",
        description: "Description for Game 38",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 39",
        swfUrl: "/games/game39.swf",
        thumbnail: "/thumbnails/game39.jpg",
        description: "Description for Game 39",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 40",
        swfUrl: "/games/game40.swf",
        thumbnail: "/thumbnails/game40.jpg",
        description: "Description for Game 40",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 41",
        swfUrl: "/games/game41.swf",
        thumbnail: "/thumbnails/game41.jpg",
        description: "Description for Game 41",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 42",
        swfUrl: "/games/game42.swf",
        thumbnail: "/thumbnails/game42.jpg",
        description: "Description for Game 42",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 43",
        swfUrl: "/games/game43.swf",
        thumbnail: "/thumbnails/game43.jpg",
        description: "Description for Game 43",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 44",
        swfUrl: "/games/game44.swf",
        thumbnail: "/thumbnails/game44.jpg",
        description: "Description for Game 44",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Music",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 45",
        swfUrl: "/games/game45.swf",
        thumbnail: "/thumbnails/game45.jpg",
        description: "Description for Game 45",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Action",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Game 46",
        swfUrl: "/games/game46.swf",
        thumbnail: "/thumbnails/game46.jpg",
        description: "Description for Game 46",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Strategy",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Game 47",
        swfUrl: "/games/game47.swf",
        thumbnail: "/thumbnails/game47.jpg",
        description: "Description for Game 47",
        tags: ["Placeholder"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Hard" as const,
        playCount: 0,
      },
      {
        title: "Game 48",
        swfUrl: "/games/game48.swf",
        thumbnail: "/thumbnails/game48.jpg",
        description: "Description for Game 48",
        tags: ["Placeholder"],
        isMultiplayer: true,
        category: "Adventure",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Pac-Man Platformer",
        swfUrl: "https://phreshhhhh.github.io/pacmanplatform/pacman%20Platformer",
        thumbnail: "https://i.postimg.cc/QdHCh2yd/Pacmanplatform-PIC.png",
        description: "Classic arcade maze game",
        tags: ["Arcade", "Classic", "Maze"],
        isMultiplayer: false,
        category: "Platform",
        difficulty: "Easy" as const,
        playCount: 0,
      },
      {
        title: "Tetris",
        swfUrl: "/games/tetris.swf",
        thumbnail: "/thumbnails/tetris.jpg",
        description: "Puzzle game of falling blocks",
        tags: ["Puzzle", "Classic", "Strategy"],
        isMultiplayer: false,
        category: "Puzzle",
        difficulty: "Medium" as const,
        playCount: 0,
      },
      {
        title: "Super Mario Bros",
        swfUrl: "/games/mario.swf",
        thumbnail: "/thumbnails/mario.jpg",
        description: "Platform adventure game",
        tags: ["Platform", "Adventure", "Classic"],
        isMultiplayer: false,
        category: "Adventure",
        difficulty: "Medium" as const,
        playCount: 0,
      },
    ];

    for (const game of games) {
      // Check if game already exists to avoid duplicates
      const existing = await ctx.db.query("games").filter(q => q.eq(q.field("title"), game.title)).take(1);
      if (existing.length === 0) {
        await ctx.db.insert("games", game);
      }
    }

    return "Games seeded successfully";
  },
});
